### ISSUE TITLE
Not able to install stencil from source

### ISSUE THREAD

**Issue by hemanthsavasere** [odpf/stencil#158]
**Describe the bug**
Not able to install stencil from the source when I execute the **make build** command to build the stencil binary file getting issues as mentioned below

 > generating ui build
make[1]: Entering directory '/home/hemanth/projects/go/stencil/ui'
make[1]: yarn: No such file or directory
make[1]: *** [Makefile:10: dep] Error 127
make[1]: Leaving directory '/home/hemanth/projects/go/stencil/ui'
make: *** [Makefile:35: ui] Error 2

**To Reproduce**
1. Clone the repository
2. Navigate to the project directory
3. Run the **make build** command

**Expected behavior**
The build should complete without any errors

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Ubuntu 22.04]
 - Go[1.18.7]

**Comment by hemanthsavasere** [comment]
Need to add yarn as one of the dependencies.

**Comment by harikrishnakanchi** [comment]
Hi @hemanthsavasere,
Yes. It has Yarn dependency. We will update the README. Thanks for pointing that out.
