### ISSUE TITLE
POST /descriptors API gives 400 instead of 409 

### ISSUE THREAD

**Issue by hariogaur** [odpf/stencil#42]
Ref: post_v1_namespaces{namespace}_descriptors

With both dryryn true & false, the API returns a 400 Bad Request while the documentation clearly states 409 Conflict.

Is this a bug or a feature?

**Comment by harikrishnakanchi** [comment]
Updated the [docs](https://odpf.gitbook.io/stencil/stencil-server/api#post__v1_namespaces_{namespace}_descriptors-responses).
