### ISSUE TITLE
Stencil Fails to Download the latest protodescriptor with version number.

### ISSUE THREAD

**Issue by sravankorumilli** [odpf/stencil#67]
**Describe the bug**
Through Stencil Client shell, download of latest proto descriptor with version number fails, the db query construction is wrong for this scenario.

**To Reproduce**
1. Upload a new descriptor through cli which is promoted to latest
2. Try to fetch the same with version number & it fails.

**Expected behavior**
Should fetch.

**Comment by NNcrawler** [comment]
Doesn't work for me as well
